"""add progress column to documents

Revision ID: 7e3c2df7cc7d
Revises: 2cd2909030d7
Create Date: 2026-06-25 20:59:24.233435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e3c2df7cc7d'
down_revision: Union[str, Sequence[str], None] = '2cd2909030d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('progress', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'progress')
    # ### end Alembic commands ###
